/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Agus
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnkoma = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnkali = new javax.swing.JButton();
        bntbagi = new javax.swing.JButton();
        btnminples = new javax.swing.JButton();
        btnsamadengan = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn1.setText("1");
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, 40));

        btn2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn2.setText("2");
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 40));

        btn3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn3.setText("3");
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 60, 40));

        btn4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn4.setText("4");
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 40));

        btn5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn5.setText("5");
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 40));

        btn6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 60, 40));

        btn7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn7.setText("7");
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 40));

        btn8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn8.setText("8");
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 40));

        btn9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn9.setText("9");
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 60, 40));

        btn0.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btn0.setText("0");
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 40));

        btnkoma.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btnkoma.setText(",");
        getContentPane().add(btnkoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 60, 40));

        btnhapus.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btnhapus.setText("c");
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 60, 40));

        btntambah.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btntambah.setText("+");
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 60, 40));

        btnkurang.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btnkurang.setText("-");
        getContentPane().add(btnkurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 60, 40));

        btnkali.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btnkali.setText("*");
        getContentPane().add(btnkali, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 60, 40));

        bntbagi.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        bntbagi.setText("/");
        getContentPane().add(bntbagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 60, 40));

        btnminples.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btnminples.setText("+/-");
        getContentPane().add(btnminples, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 40));

        btnsamadengan.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btnsamadengan.setText("=");
        getContentPane().add(btnsamadengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 130, 40));

        jTextField1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntbagi;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkali;
    private javax.swing.JButton btnkoma;
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnminples;
    private javax.swing.JButton btnsamadengan;
    private javax.swing.JButton btntambah;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
